spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/employee_management?useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

logging:
  level:
    root: INFO
    com.example.employeemanagement: INFO
