spring:
  application:
    name: employee-management
  datasource:
    url: jdbc:h2:mem:employee_db;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true

server:
  port: 8080
